"""Constantes de classification pour `structured`.

Donnees pures (aliases de sections, langues, contrats, synonymes) extraites de
`structured.py` pour reduire sa taille. Aucune logique ici — uniquement des
mappings et listes.
"""
from __future__ import annotations

_SECTION_ALIASES: list[tuple[str, tuple[str, ...]]] = [
    (
        "summary",
        (
            "profil",
            "profile",
            "about",
            "about me",
            "a propos",
            "à propos",
            "bio",
            "biographie",
            "who am i",
            "resume",
            "résumé",
            "summary",
            "presentation",
            "présentation",
            "profil professionnel",
            "objectif",
        ),
    ),
    (
        "skills",
        (
            "competences",
            "compétences",
            "skills",
            "stack",
            "stack technique",
            "tech stack",
            "technologies",
            "outils",
            "outillage",
            "frameworks",
            "langages",
            "expertise",
            "hard skills",
            "soft skills",
            "capabilities",
            "aptitudes",
            "technical skills",
            "competences techniques",
        ),
    ),
    (
        "experience",
        (
            "experience",
            "expérience",
            "experiences",
            "expériences",
            "work experience",
            "professional experience",
            "parcours",
            "missions",
            "mission",
            "employment history",
            "career",
            "carriere",
            "carrière",
            "projects",
            "project",
            "projets",
            "projet",
            "realisations",
            "réalisations",
            "achievements",
            "portfolio",
        ),
    ),
    (
        "education",
        (
            "formation",
            "education",
            "études",
            "etudes",
            "diplome",
            "diplôme",
            "diplomes",
            "diplômes",
            "academique",
            "académique",
            "scolarite",
            "scolarité",
            "universite",
            "université",
            "school",
        ),
    ),
    (
        "certifications",
        (
            "certification",
            "certifications",
            "certificat",
            "certificats",
            "certifications professionnelles",
        ),
    ),
    (
        "languages",
        (
            "langues",
            "languages",
            "language",
            "langues parlées",
            "langues parlees",
            "language skills",
            "bilingue",
            "bilingual",
        ),
    ),
    (
        "job_required",
        (
            "competences requises",
            "compétences requises",
            "contrainte forte",
            "contraintes fortes",
            "contrainte forte du projet",
            "responsabilites",
            "responsabilités",
            "responsabilites principales",
            "responsabilités principales",
            "taches",
            "tâches",
            "activites",
            "activités",
            "qualifications",
            "profile wanted",
            "profil attendu",
            "profil ideal",
            "profil idéal",
            "requirements",
            "must have",
            "prérequis",
            "pre requis",
            "profil recherché",
            "profil recherche",
            "exigences",
            "description du poste",
            "description du job",
            "role",
        ),
    ),
    (
        "job_nice",
        (
            "nice to have",
            "atouts",
            "atout",
            "bonus",
            "souhaité",
            "souhaite",
            "souhaitable",
            "apprécié",
            "apprecie",
            "appréciée",
            "plus",
        ),
    ),
    (
        "contract",
        (
            "contrat",
            "type de contrat",
            "statut",
            "disponibilite",
            "disponibilité",
            "duree",
            "durée",
        ),
    ),
    (
        "location",
        (
            "localisation",
            "location",
            "ville",
            "adresse",
            "teletravail",
            "télétravail",
            "remote",
            "hybride",
            "mobilite",
            "mobilité",
        ),
    ),
    (
        "contact",
        (
            "contact",
            "coordonnees",
            "coordonnées",
            "email",
            "e-mail",
            "telephone",
            "téléphone",
            "tel",
            "mobile",
            "linkedin",
            "github",
        ),
    ),
    (
        "hobbies",
        (
            "interets",
            "intérêts",
            "centres d'interet",
            "centres d'intérêt",
            "loisirs",
            "hobbies",
            "passions",
            "sports",
        ),
    ),
]

_LANGUAGE_ALIASES: dict[str, str] = {
    "francais": "français",
    "french": "français",
    "anglais": "anglais",
    "english": "anglais",
    "espagnol": "espagnol",
    "spanish": "espagnol",
    "portugais": "portugais",
    "portuguese": "portugais",
    "allemand": "allemand",
    "german": "allemand",
    "arabe": "arabe",
    "arabic": "arabe",
}

_NOISE_TERMS = {
    "year",
    "years",
    "annee",
    "annees",
    "experience",
    "experiences",
    "exp",
    "month",
    "months",
    "ans",
    "interet",
    "interets",
    "interest",
    "interests",
    "loisir",
    "loisirs",
    "hobby",
    "hobbies",
}

_CONTRACT_ALIASES: list[tuple[str, str]] = [
    ("cdi", "CDI"),
    ("cdd", "CDD"),
    ("freelance", "Freelance"),
    ("independant", "Freelance"),
    ("indépendant", "Freelance"),
    ("consultant", "Freelance"),
    ("stage", "Stage"),
    ("alternance", "Alternance"),
    ("temps plein", "Temps plein"),
    ("temps partiel", "Temps partiel"),
    ("full time", "Temps plein"),
    ("part time", "Temps partiel"),
    ("hybride", "Hybride"),
    ("teletravail", "Télétravail"),
    ("télétravail", "Télétravail"),
    ("remote", "Télétravail"),
    ("full remote", "Télétravail"),
]

_BUILTIN_SKILL_SYNONYMS: dict[str, str] = {
    "js": "javascript",
    "javascript": "javascript",
    "ts": "typescript",
    "typescript": "typescript",
    "node js": "nodejs",
    "nodejs": "nodejs",
    "node": "nodejs",
    "node js express": "nodejs",
    "node js api": "nodejs",
    "node js backend": "nodejs",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "py": "python",
    "python": "python",
    "c#": "csharp",
    "c sharp": "csharp",
    "c++": "cplusplus",
    "c plus plus": "cplusplus",
    "react js": "react",
    "reactjs": "react",
    "react": "react",
    "vue js": "vue",
    "vuejs": "vue",
    "vue": "vue",
    "fast api": "fastapi",
    "fastapi": "fastapi",
    "docker": "docker",
    "k8s": "kubernetes",
    "kubernetes": "kubernetes",
    "aws": "aws",
    "azure": "azure",
    "ml": "machinelearning",
    "machine learning": "machinelearning",
    "data science": "datascience",
}
