"""add priority_keywords_missing to match_results

Revision ID: 69fd6118fc1d
Revises: 7a52bf516183
Create Date: 2026-09-15 08:42:55.987059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fd6118fc1d'
down_revision = '7a52bf516183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_results', sa.Column('priority_keywords_missing', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_results', 'priority_keywords_missing')
    # ### end Alembic commands ###
