"""cleanup pre-existing schema drift

Revision ID: 7a52bf516183
Revises: 0019_job_scoring_profile
Create Date: 2026-09-14 10:18:42.562755

Hand-edited after --autogenerate (2026-09-14 schema-drift audit, see the
non-blocking `alembic check` CI step added the same day): the raw
autogenerated diff also proposed DROPPING the cv_embeddings/job_embeddings
ivfflat vector-similarity indexes and the extracted_text parsed-profile
index. Those are real, deliberately-created indexes (migration
0004_embeddings_index) never declared in the ORM models -- autogenerate
only sees "the DB has an index the model doesn't know about" and asks to
remove it, which would have silently killed vector search performance in
production. Left out entirely; only the columns below are touched.

Every NOT NULL alter is preceded by a defensive backfill (there should be
no NULLs given every affected column has a server_default, but this makes
the migration safe regardless of what 3+ years of hand-written migrations
actually left behind, instead of assuming and finding out on production).
The parser_feedback.user_id FK is genuinely new (migration 0009 never
created it at all, unlike the session_id FKs elsewhere in this repo) and
is preceded by nulling out any orphaned references so the ADD CONSTRAINT
can't fail on unknown production data.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a52bf516183'
down_revision = '0019_job_scoring_profile'
branch_labels = None
depends_on = None

# (table, column) pairs that get a defensive backfill + NOT NULL.
_TIMESTAMP_NOT_NULL_COLUMNS = [
    ('cv_documents', 'created_at'),
    ('cv_documents', 'updated_at'),
    ('cv_embeddings', 'created_at'),
    ('cv_embeddings', 'updated_at'),
    ('event_logs', 'created_at'),
    ('extracted_text', 'created_at'),
    ('extracted_text', 'updated_at'),
    ('job_documents', 'created_at'),
    ('job_documents', 'updated_at'),
    ('job_embeddings', 'created_at'),
    ('job_embeddings', 'updated_at'),
    ('match_results', 'created_at'),
    ('match_results', 'updated_at'),
    ('score_results', 'created_at'),
    ('users', 'created_at'),
    ('users', 'updated_at'),
]


def upgrade():
    for table, column in _TIMESTAMP_NOT_NULL_COLUMNS:
        op.execute(f"UPDATE {table} SET {column} = now() WHERE {column} IS NULL")
        op.alter_column(
            table, column,
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text('now()'),
        )

    # Never actually existed as a real FK constraint in the DB (migration
    # 0009_parser_feedback only ever created a plain integer column) --
    # null out any reference to a since-deleted user first so this can't
    # fail on production data we can't inspect from here.
    op.execute(
        "UPDATE parser_feedback SET user_id = NULL "
        "WHERE user_id IS NOT NULL AND user_id NOT IN (SELECT id FROM users)"
    )
    op.create_foreign_key(
        'fk_parser_feedback_user', 'parser_feedback', 'users', ['user_id'], ['id']
    )


def downgrade():
    op.drop_constraint('fk_parser_feedback_user', 'parser_feedback', type_='foreignkey')
    for table, column in reversed(_TIMESTAMP_NOT_NULL_COLUMNS):
        op.alter_column(
            table, column,
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text('now()'),
        )
